# Generated by Django 4.0.6 on 2022-08-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TyprrrUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typrrruser',
            name='best_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='typrrruser',
            name='key_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
