# Generated by Django 4.0.6 on 2023-06-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TyprrrUser', '0002_typrrruser_best_speed_typrrruser_key_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typrrruser',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
